---

branches:
  - name: main
    prerelease: false
  - name: master
    prerelease: false

plugins:

  # Analyze commits to decide release type (major/minor/patch)
  - "@semantic-release/commit-analyzer"

  # Generate release notes
  - "@semantic-release/release-notes-generator"

  # Update CHANGELOG.md
  - - "@semantic-release/changelog"

  # Update Github release
  - - "@semantic-release/github"

  # Commit galaxy.yml + changelog changes
  - - "@semantic-release/git"
    - assets:
        - CHANGELOG.md
      message: 'chore(release): ${nextRelease.version} [skip ci]


        ${nextRelease.notes}'
