---

- name: Install OS packages
  ansible.builtin.package:
    name: "{{ radicale_os_packages }}"
    state: present

- name: Install PIP packages into a virtualenv
  ansible.builtin.include_tasks:
    file: venv.yml
  vars:
    venv_root: "{{ radicale_venv_root }}"
    venv_packages: "{{ radicale_pip_packages }}"
