---

- name: Install dependencies using pip
  ansible.builtin.pip:
    name: "{{ radicale_pip_packages }}"
    executable: pip3

- name: Install radicale using pip
  ansible.builtin.pip:
    name: radicale
    version: "{{ radicale_version }}"
    executable: pip3
    extra_args: "{{ '--upgrade' if radicale_version == 'latest' else omit }}"
  notify: Restart radicale
